codecov:
  notify: {}
  require_ci_to_pass: false

comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]

coverage:
  status:
    patch:
      default:
        if_ci_failed: failure
        if_no_uploads: success
        if_not_found: success
        target: 95.0
    project:
      default: false
      library:
        if_ci_failed: failure
        if_no_uploads: error
        if_not_found: success
        target: 90.0