name: junifer-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10,<=3.13
  - click>=8.1.3,<8.2
  - numpy>=1.26.0,<2.0.0
  - scipy>=1.10.0,<=1.15.0
  - pandas>=2.0.0,<2.3.0
  - nibabel>=5.2.0,<5.4.0
  - nilearn>=0.10.3,<=0.10.4
  - sqlalchemy>=2.0.25,<=2.1.0
  - ruamel.yaml>=0.17,<0.19
  - h5py>=3.10
  - tqdm>=4.66.1,<4.67.0
  - templateflow>=23.0.0
  - lapy>=1.0.0,<2.0.0
  - lazy_loader==0.4
  - importlib_metadata
  - looseversion==1.3.0
  - bctpy==0.6.0
  - neurokit2>=0.1.7
  - seaborn>=0.13.0,<0.14.0
  - sphinx>=7.3.0,<8.1.0
  - sphinx-gallery>=0.17.0,<0.18.0
  - furo>=2024.4.27,<2024.9.0
  - numpydoc>=1.6.0,<1.9.0
  - sphinx-copybutton>=0.5.1,<0.5.3
  - towncrier>=23.10.0,<24.7.0
  - sphinxcontrib-mermaid>=0.8.1,<0.10
  - sphinxcontrib-towncrier==0.4.0a0
  - setuptools-scm>=8
  - tox
  - pre-commit
  - ruff>=0.1.0
  - ipykernel
  - pytest-cov
  - pytest
  - codespell
  - tomli
  - pip
  - pip:
    - datalad>=1.0.0,<1.2.0
    - julearn==0.3.3
    - junifer_data==1.3.0
