name: junifer-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<=3.11
  - click=8.1.*
  - numpy>=1.22,<1.27
  - pandas>=1.4.0,<2.2
  - nibabel>=3.2.0,<5.2
  - nilearn>=0.9.0,<=0.10.1
  - sqlalchemy>=1.4.27,<= 2.0.21
  - ruamel.yaml=0.17.*
  - h5py>=3.8,<=3.9
  - seaborn>=0.11,<=0.13
  - sphinx>=5.3,<7.3
  - sphinx-gallery>=0.11.0,<0.15.0
  - furo>=2022.9.29,<2023.10.0
  - numpydoc>=1.5.0,<1.6
  - sphinx-copybutton>=0.5.1,<0.5.3
  - towncrier>=22.12.0,<23.7
  - sphinxcontrib-mermaid>=0.8.1,<0.10
  - tox
  - ipykernel
  - pytest-cov
  - pytest
  - black
  - ruff
  - codespell
  - pip
  - pip:
    - datalad>=0.15.4,<0.20
    - julearn==0.3.0
