name: junifer-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - click=8.1.*
  - numpy>=1.22,<1.24
  - pandas>=1.4.0,<1.6
  - nibabel>=3.2.0,<4.1
  - nilearn>=0.9.0,<=0.10.0
  - sqlalchemy>=1.4.27,<= 1.5.0
  - ruamel.yaml=0.17.*
  - h5py=3.8.*
  - seaborn=0.11.*
  - Sphinx=5.3.*
  - sphinx-gallery=0.11.*
  - furo>=2022.9.29,<2023.0.0
  - numpydoc=1.5.*
  - sphinx-copybutton=0.5.*
  - towncrier=22.12.*
  - sphinxcontrib-mermaid=0.8.*
  - tox
  - ipykernel
  - pytest-cov
  - pytest
  - black
  - ruff
  - codespell
  - pip
  - pip:
    - datalad>=0.15.4,<0.19
    - julearn==0.2.5
