name: Dataset Request
description: Request to include a dataset
title: "[DAT]: "
labels: ["dataset", "triage"]
assignees:
  - fraimondo
  - synchon
body:
  - type: markdown
    attributes:
      value: |
        Fill in this form if you want that junifer includes a new dataset.

        As a reminder, junifer supports customising the `PatternDataGrabber` and `PatternDataladDatagrabber` which should work in most cases.

        If it is a widely used dataset, we could alternatevely create a new _DataGrabber_ that simplifies the usage, by already configuring the underlying `PatternDataGrabber` or `PatternDataladDatagrabber`
  - type: textarea
    id: which-dataset
    attributes:
      label: Which dataset is it?
      description: |
        Please include the source, description, and why we should include it in junifer.
      placeholder: Convince us!
    validations:
      required: true
  - type: dropdown
    id: class
    attributes:
      label: Implementation
      description: Have you implemented this dataset with any of this classes?
      options:
        - PatternDataGrabber
        - PatternDataladDatagrabber
        - Other class
        - Did not implement anything
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Your implementation
      description: |
        If you user any of the existing classes for this dataset, please copy and paste your implementation here. You can also post a link to a gist or github repository with the implementation.
      render: shell
  - type: checkboxes
    id: access
    attributes:
      label: Dataset access restrictions
      description: Please mark all of the applicable conditions to use this dataset
      options:
        - label: Public and open access (no registration)
        - label: Public and open access (registration required)
        - label: Restricted access (needs approuval)
        - label: Available only in specific locations (Juseless, Jureca)
  - type: textarea
    id: extra
    attributes:
      label: Anything else to say?
      description:
      placeholder: ...
