name: Run Tests

on: 
  push:
    paths-ignore:
      - 'junifer/**'
  pull_request:
    paths-ignore:
      - 'junifer/**'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - run: 'echo "No build required"'
