name: Run Tests

on: 
  push:
    paths-ignore:
      - 'junifer/**'
  pull_request:
    paths-ignore:
      - 'junifer/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
