name: Run Tests

on: 
  push:
    paths-ignore:
      - 'junifer/**'
  pull_request:
    paths-ignore:
      - 'junifer/**'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - run: 'echo "No build required"'
      - name: Create mock coverage.xml file
        run: |
          echo '<?xml version="1.0" ?>' > coverage.xml
          echo '<coverage version="6.5.0" timestamp="1666772572187" lines-valid="1" lines-covered="1" line-rate="1" branches-valid="1" branches-covered="1" branch-rate="1" complexity="0"> </coverage>' >> coverage.xml
        if: matrix.python-version == 3.9
      - name: Upload mock coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: mock
        if: success() && matrix.python-version == 3.9