name: Build and publish docs

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
    # Sequence of patterns matched against refs/tags
    tags:
      - v*
  workflow_dispatch: {}

jobs:
  build-docs:
    runs-on: [self-hosted, linux, x64, data-v7]
    steps:
    - name: Check ANTs
      run: |
        echo "Using ANTs : $(antsRegistration --version)"
    - name: Check tooling
      run: |
        which make git-annex jq
        ls -d "$HOME"/junifer_data/v7
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        # require all of history to see all tagged versions' docs
        fetch-depth: 0
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.12"
    - name: Set up uv
      uses: astral-sh/setup-uv@v10.2.0
    - name: Install Python dependencies
      run: |
        uv sync --locked --extra docs
    - name: Configure Git for DataLad
      run: |
        git config --global user.email "junifer-runner@github.com"
        git config --global user.name "GitHub Runner"
    - name: Checkout gh-pages
      # As we already did a deploy of gh-pages above, it is guaranteed to be there
      # so check it out so we can selectively build docs below
      uses: actions/checkout@v7
      with:
          ref: gh-pages
          path: docs/_build
    - name: Build docs
      # Build all the versions with sphinx-polyversion; the versions already
      # in gh-pages are kept and only the missing ones are built
      # https://github.com/actions/checkout/issues/1169#issuecomment-2291682583
      run: |
        git config --global --add safe.directory $(pwd)
        uv run make -C docs/ html
        touch docs/_build/.nojekyll
        cp docs/redirect.html docs/_build/index.html
    - name: Publish docs to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build
        keep_files: true
