name: Build and preview docs

on:
  # Docs for main and tags are built by docs.yml
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: [self-hosted, linux, x64, data-v8]
    permissions:
      # Needed for preview deploy
      pull-requests: write
      contents: write
    steps:
    - name: Check ANTs
      if: github.event.action != 'closed' # The build is not needed when the preview is removed
      run: |
        echo "Using ANTs : $(antsRegistration --version)"
    - name: Check tooling
      if: github.event.action != 'closed' # The build is not needed when the preview is removed
      run: |
        which make git-annex jq
        ls -d "$HOME"/junifer_data/v7
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up Python
      if: github.event.action != 'closed' # The build is not needed when the preview is removed
      uses: actions/setup-python@v7
      with:
        python-version: "3.12"
    - name: Set up uv
      if: github.event.action != 'closed' # The build is not needed when the preview is removed
      uses: astral-sh/setup-uv@v10.2.0
    - name: Install Python dependencies
      if: github.event.action != 'closed' # The build is not needed when the preview is removed
      run: |
        uv sync --locked --extra docs
    - name: Configure Git for DataLad
      if: github.event.action != 'closed' # The build is not needed when the preview is removed
      run: |
        git config --global user.email "junifer-runner@github.com"
        git config --global user.name "GitHub Runner"
    - name: Test build docs
      if: github.event.action != 'closed' # The build is not needed when the preview is removed
      run: |
        BUILDDIR=_build/main uv run make -C docs/ local
    - name: Deploy preview
      if: github.event_name == 'pull_request'
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: docs/_build/main
